# Generated by Django 3.2.12 on 2023-08-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_auto_20230825_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='verification_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='verified_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
